[2021-09-11 20:34:14] [INFO] [common.py:74] <module>: Initializing the common module.
[2021-09-11 20:34:14] [INFO] [common.py:134] <module>: Changing the recursion limit from 1000 to 1000000 at the user's request.
[2021-09-11 20:34:15] [INFO] [project.py:33] <module>: Loading libclang from "/usr/lib/x86_64-linux-gnu/libclang-10.so.1".
[2021-09-11 20:34:15] [INFO] [project.py:42] <module>: Loaded libclang successfully.
[2021-09-11 20:34:15] [INFO] [database.py:34] __init__: Connecting to the database with the following configurations: {'host': '127.0.0.1', 'port': '3306', 'user': 'admin', 'password': '', 'database': 'software', 'sql_mode': 'ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'}
[2021-09-11 20:34:15] [INFO] [database.py:42] __init__: Autocommit is False.
[2021-09-11 20:34:15] [INFO] [create_alert_and_cwe_tables_in_database.py:31] create_alert_and_cwe_tables_in_database: Creating the VULNERABILITY_CATEGORY table.
[2021-09-11 20:34:15] [INFO] [create_alert_and_cwe_tables_in_database.py:47] create_alert_and_cwe_tables_in_database: Creating the CWE_INFO table.
[2021-09-11 20:34:15] [INFO] [create_alert_and_cwe_tables_in_database.py:82] create_alert_and_cwe_tables_in_database: Inserting the default values in the VULNERABILITY_CATEGORY and CWE_INFO tables.
[2021-09-11 20:34:15] [INFO] [create_alert_and_cwe_tables_in_database.py:106] create_alert_and_cwe_tables_in_database: Creating the SAT table.
[2021-09-11 20:34:15] [INFO] [create_alert_and_cwe_tables_in_database.py:120] create_alert_and_cwe_tables_in_database: Inserting the default values in the SAT table.
[2021-09-11 20:34:15] [INFO] [create_alert_and_cwe_tables_in_database.py:135] create_alert_and_cwe_tables_in_database: Creating the RULE table.
[2021-09-11 20:34:15] [INFO] [create_alert_and_cwe_tables_in_database.py:158] create_alert_and_cwe_tables_in_database: Creating the RULE_CWE_INFO table.
[2021-09-11 20:34:15] [INFO] [project.py:126] get_project_list_from_config: Loading the project "Glibc" (glibc) with the following configurations: {'short_name': 'glibc', 'database_id': 5, 'database_name': 'glibc', 'github_data_name': 'glibc', 'vendor_id': 72, 'product_id': 767, 'url_pattern': 'sourceware', 'master_branch': 'master', 'language': 'c', 'include_directory_path': 'include', 'repository_path': '/home/admin/estagio-2020-2021/estagio-software-vulnerabilities-2020-2021/repositories/glibc', 'output_directory_path': 'output/final', 'scrape_all_branches': False}
[2021-09-11 20:34:15] [INFO] [project.py:87] __init__: Loaded the project "Glibc" located in "/home/admin/estagio-2020-2021/estagio-software-vulnerabilities-2020-2021/repositories/glibc".
[2021-09-11 20:34:15] [INFO] [project.py:126] get_project_list_from_config: Loading the project "Apache HTTP Server" (apache) with the following configurations: {'short_name': 'apache', 'database_id': 4, 'database_name': 'httpd', 'github_data_name': 'httpd', 'vendor_id': 45, 'product_id': 66, 'url_pattern': 'apache', 'master_branch': 'trunk', 'language': 'c', 'include_directory_path': 'include', 'repository_path': '/home/admin/estagio-2020-2021/estagio-software-vulnerabilities-2020-2021/repositories/httpd', 'output_directory_path': 'output/final', 'scrape_all_branches': False}
[2021-09-11 20:34:15] [INFO] [project.py:87] __init__: Loaded the project "Apache HTTP Server" located in "/home/admin/estagio-2020-2021/estagio-software-vulnerabilities-2020-2021/repositories/httpd".
[2021-09-11 20:34:15] [INFO] [project.py:126] get_project_list_from_config: Loading the project "Xen" (xen) with the following configurations: {'short_name': 'xen', 'database_id': 3, 'database_name': 'xen', 'github_data_name': 'xen', 'vendor_id': 6276, 'product_id': None, 'url_pattern': 'xen', 'master_branch': 'master', 'language': 'c', 'include_directory_path': 'xen/include', 'repository_path': '/home/admin/estagio-2020-2021/estagio-software-vulnerabilities-2020-2021/repositories/xen', 'output_directory_path': 'output/final', 'scrape_all_branches': False}
[2021-09-11 20:34:15] [INFO] [project.py:87] __init__: Loaded the project "Xen" located in "/home/admin/estagio-2020-2021/estagio-software-vulnerabilities-2020-2021/repositories/xen".
[2021-09-11 20:34:15] [INFO] [project.py:126] get_project_list_from_config: Loading the project "Linux Kernel" (kernel) with the following configurations: {'short_name': 'kernel', 'database_id': 2, 'database_name': 'kernel', 'github_data_name': 'linux', 'vendor_id': 33, 'product_id': 47, 'url_pattern': 'linux|kernel|redhat', 'master_branch': 'master', 'language': 'c', 'include_directory_path': 'include', 'repository_path': '/home/admin/estagio-2020-2021/estagio-software-vulnerabilities-2020-2021/repositories/linux', 'output_directory_path': 'output/final', 'scrape_all_branches': False}
[2021-09-11 20:34:15] [INFO] [project.py:87] __init__: Loaded the project "Linux Kernel" located in "/home/admin/estagio-2020-2021/estagio-software-vulnerabilities-2020-2021/repositories/linux".
[2021-09-11 20:34:15] [INFO] [project.py:126] get_project_list_from_config: Loading the project "Mozilla" (mozilla) with the following configurations: {'short_name': 'mozilla', 'database_id': 1, 'database_name': 'mozilla', 'github_data_name': 'mozilla', 'vendor_id': 452, 'product_id': None, 'url_pattern': 'mozilla', 'master_branch': 'master', 'language': 'c++', 'include_directory_path': None, 'repository_path': '/home/admin/estagio-2020-2021/estagio-software-vulnerabilities-2020-2021/repositories/gecko-dev', 'output_directory_path': 'output/final', 'scrape_all_branches': False}
[2021-09-11 20:34:15] [INFO] [project.py:87] __init__: Loaded the project "Mozilla" located in "/home/admin/estagio-2020-2021/estagio-software-vulnerabilities-2020-2021/repositories/gecko-dev".
[2021-09-11 20:34:15] [INFO] [create_alert_and_cwe_tables_in_database.py:189] create_alert_and_cwe_tables_in_database: Creating the ALERT table.
[2021-09-11 20:34:15] [INFO] [create_alert_and_cwe_tables_in_database.py:221] create_alert_and_cwe_tables_in_database: Creating the ALERT_FUNCTION table.
[2021-09-11 20:34:15] [INFO] [create_alert_and_cwe_tables_in_database.py:243] create_alert_and_cwe_tables_in_database: Creating the ALERT_CLASS table.
[2021-09-11 20:34:15] [INFO] [create_alert_and_cwe_tables_in_database.py:265] create_alert_and_cwe_tables_in_database: Committing changes.
[2021-09-11 20:34:15] [INFO] [create_alert_and_cwe_tables_in_database.py:270] <module>: Finished running.
